### ISSUE TITLE
Is there any way to set indentation level?

### ISSUE THREAD

**Issue by petk** [BlankSpruce/gersemi#15]
Can the indentation level be set to 2 in the configuration somehow? Thank you.

**Comment by BlankSpruce** [comment]
I don't intend to support that. The idea for this formatter is to have predictable formatting wherever you go. Black, which is a major inspiration here, also doesn't support that.

**Comment by petk** [comment]
Of course, it's your project. No problem. However, this is weird to be honest. Comparing CMake code with Python is comparing two different things. CMake code never was indented with 4 spaces. It is mostly indented with 2. Then we need to find some decent normal customizable formatter in the CMake ecosystem...

**Comment by BlankSpruce** [comment]
The comparison wasn't about comparing CMake code to Python but about formatter with intentionally limited set of configuration options. I honestly rather abide by the rules imposed by the formatter (and I mean any other formatter, not necessarily gersemi) than to get involved in not so rare, especially in corporate environments, bikeshedding over what is the proper size of indentation. With me putting the finger on the scale you can always use an argument "see, gersemi's author made this dumb choice so we have to live with that". Such decision cuts most likely unproductive discussions.

Another thing about number of spaces per indentation level: why 2? Although I have some observation on why a bit bigger than 2 indentation matters and I'm not trying to argue that 4 is superior. I'm simply trying to understand why this particular option is something you'd desire and why exactly you'd desire 2. Given that your original post didn't show any consideration on "why" question - rightfully so, this was simple genuine question - neither did my previous response provide any deeper insight.

In terms of CMake code formatting in my experience 4 spaces is the most common one to appear in the hand-formatted code. I don't deny there are also codebases with different rule (like [CMake codebase](https://gitlab.kitware.com/cmake/cmake/-/blob/master/CMakeLists.txt)), I've seen some of those too but they were the minority. I'm guessing that this is somehow related to the defaults provided in formatters for other languages or editors. I'm aware of such default at least in aforementioned black, [rustfmt](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#tab_spaces), [VSCode](https://code.visualstudio.com/docs/editor/codebasics#_indentation). That being said the first paragraph is my main motivation for such choice.

**Comment by tueda** [comment]
For reference, as far as other formatter defaults are concerned, [`cmake-format`](https://github.com/cheshirekow/cmake_format) uses 2 spaces by default (and it is configurable). Many C/C++/Fortran projects are built with CMake and maybe users want to use the same (or at least a similar) style for indentations in the main programming language and CMake scripts. [`clang-format`](https://clang.llvm.org/docs/ClangFormat.html) allows users to follow several varieties of predefined styles (the default style uses 2 spaces). [`fprettify`](https://github.com/pseewald/fprettify) uses 3 spaces by default (configurable). By the way, in the [KDE CMake Coding Style](https://community.kde.org/Policies/CMake_Coding_Style), examples are written with 3-space indentations. If you want a "dumb choice" then I would recommend odd numbers than even numbers, though personally I think most of the CMake scripts I see use 2 spaces.

Considering diverse ecosystems with CMake in the [absence of an official style guide](https://discourse.cmake.org/t/feature-request-universal-enforcement-of-cmake-script-formatting/4852), IMHO, it is natural to allow each project to choose its style. This is a completely different situation than with Python or Rust; they have the official recommendations. (But it is OK to try to unify the world with your project.)

**Comment by PatTheMav** [comment]
I don't mind formatters being opinionated (Black comes to mind), but this specific choice makes it hard to switch a large CMake codebase that used to be formatted using `cmake-format` to `gersemi`, as the amount of (unnecessary) formatting changes just becomes too large.

For adoption of `gersemi` by existing projects it would be a boon if it could be made to use the `cmake-format` style (similar to how `clang-format` has built-in styles). That would make it easier for existing projects to adopt the new, actively-maintained formatter.

**Comment by BlankSpruce** [comment]
I've reopened this issue since I want to ponder on the idea of supporting other indentation levels. Having an easier adoption path is certainly something to consider.

@PatTheMav 
I don't follow what's the difficulty in applying a format and commiting one commit for that change. I might guess that you're worried about how it affects utilities like `git blame`* but other than that I'm honestly clueless.

I don't want to support `cmake-format` style in any capacity. Even more, I won't accept PR that implements that. If one finds value in `cmake-format`, which is perfectly reasonable choice, one should consider supporting that project instead.

\* - it can be mitigated with [blame.ignoreRevsFile](https://git-scm.com/docs/git-config#Documentation/git-config.txt-blameignoreRevsFile) coupled with usual `.git-blame-ignore-revs` file in the repository.

**Comment by PatTheMav** [comment]
We already regularly add commits that just contain changes introduced by `clang-format` already, but in general we change the formatter configuration first to limit the changes introduced to an absolute minimum. 

For a big public open source project, the changes introduced by `gersemi` would affect all CMake files (which for us at this point would entail lots of changes to 373 CMake files), which in turn would require quite a few people to review the changes and inevitably lead to discussions of "can't we just change the formatter to introduce less unnecessary changes?" (and we're back on the topic of adoption).

As mentioned, just being able to set indentation to 2 spaces (instead of 4) reduces the amount of changes tremendously (though it'd still be over 350 files to review, but most of them would just change multi-line command invocations).

**Comment by BlankSpruce** [comment]
If I understand you correctly it boils down to:
- lack of trust that the produced output is "just formatting",
- necessity to check that the prodcued output is consistent and the formatting is helpful

for which you require code review. That's somewhat understandable since no formatter is perfect although I have to wonder if code review is in this case an efficient way to deal with that.

Thanks for raising that point.

**Comment by PatTheMav** [comment]
> If I understand you correctly it boils down to:
> 
> * lack of trust that the produced output is "just formatting",
> * necessity to check that the prodcued output is consistent and the formatting is helpful
> 
> for which you require code review. That's somewhat understandable since no formatter is perfect although I have to wonder if code review is in this case an efficient way to deal with that.
> 
> Thanks for raising that point.

It's less trust (I have no worries about that to be honest) and about fatigue/scepticism about formatting changes, especially by "opinionated" formatters. Being able to lower the amount of changes by turn has the chance to be met with less resistance, especially if it also requires maintainers to change their local toolchains as well (my goal being to replace our current use of `cmake-format` with `gersemi`) because proper formatting is mandatory for our PRs.

**Comment by BlankSpruce** [comment]
I think I've found much stronger argument than provided by @PatTheMav, specifically what's written [here](https://github.com/prettier/prettier/issues/7475#issuecomment-668544890). While I stand on the position that the fewer configuration knobs the better I certainly don't intend to alienate programmers that would prefer other indentation style for reasons other than stylistic taste. That being said I won't change the default because I favour maintaining backward compatibility as much as sensible.

I'd also like to have it available as one option instead of two option tandem like it happens in other tools, examples I'm aware of: 
- Prettier [Tab Width](https://prettier.io/docs/en/options.html#tab-width) and [Tabs](https://prettier.io/docs/en/options.html#tabs).
- rustfmt [hard_tabs](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#hard_tabs) and [tab_spaces](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#tab_spaces).
- clang-format [UseTab](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#usetab) and [IndentWidth](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#indentwidth) 

I need to come up with a good name and easy to understand syntax. Currently I'm thinking about something like that in pseudo BNF:
 `--indent=("tabs"|[number])`

so that the default remains `--indent=4` while other options can be expressed as `--indent=2` or `--indent=tabs`.

**Comment by BlankSpruce** [comment]
@petk @PatTheMav @tueda 
If you were so kind to test current master on your respective codebases I'd be grateful. I'll wait with the release of 0.12.0 for a couple of days because I'd like to make sure that there are no regressions.

**Comment by PatTheMav** [comment]
Looks good overall, I've filed #18 and #19 with the only things that jumped at me that I'd describe as making the formatting "worse" than before. All other changes are logically consistent with `gersemi`'s formatting rules and seem like worth the change.

There's also the case of our custom `set_target_properties` function not having its parameters broken up (the function uses `cmake_parse_arguments` so `gersemi` is able to interpret the parameters), but it's interestingly not consistent with the original:

```
# Our custom property setter:
set_target_xcode_properties(
  <target>
  PROPERTIES PRODUCT_NAME <target>
             PRODUCT_BUNDLE_IDENTIFIER <bundle identifier>
             MARKETING_VERSION <version>
             GENERATE_INFOPLIST_FILE YES
             INFOPLIST_FILE ""
             INFOPLIST_KEY_CFBundleDisplayName <target>
             INFOPLIST_KEY_NSHumanReadableCopyright <copyright>
)

# The default property setter:
set_target_properties(
  <target>
  PROPERTIES
    FRAMEWORK_VERSION A
    MACOSX_FRAMEWORK_IDENTIFIER <identifier>
    [...]
)
```

The arguments for the Xcode property setter are specified via:
```
  set(options "")
  set(oneValueArgs "")
  set(multiValueArgs PROPERTIES)
  cmake_parse_arguments(PARSE_ARGV 0 _STXP "${options}" "${oneValueArgs}" "${multiValueArgs}")
```

I'm not opposed to the formatting being kept stable, but I am curious why the `PROPERTIES` are not indented on the next line but instead neatly kept aligned as-is.

**Comment by BlankSpruce** [comment]
In regards to `set_target_xcode_properties` I've added it to my test suite with proposed definition and the formatting looks correct*
https://github.com/BlankSpruce/gersemi/blob/dev/tests/formatter/set_target_xcode_properties.out.cmake

And this is how it looks like when definition isn't provided:
https://github.com/BlankSpruce/gersemi/blob/dev/tests/formatter/set_target_xcode_properties_without_proper_definition.out.cmake

\* - this is a limitation of current approach that gersemi isn't able to produce exact two-argument groupping as it does for builtin `set_target_properties` since there's no way to inform gersemi about that specificity.

**Comment by petk** [comment]
Sounds good to me. Thanks for integrating this. I can't test this ATM, but I will recheck it in the future for sure. Formatting CMake code is very useful feature.

**Comment by BlankSpruce** [comment]
> Looks good overall, I've filed #18 and #19 with the only things that jumped at me that I'd describe as making the formatting "worse" than before. All other changes are logically consistent with `gersemi`'s formatting rules and seem like worth the change.
> 
> There's also the case of our custom `set_target_properties` function not having its parameters broken up (the function uses `cmake_parse_arguments` so `gersemi` is able to interpret the parameters), but it's interestingly not consistent with the original:
> 
> ```
> # Our custom property setter:
> set_target_xcode_properties(
>   <target>
>   PROPERTIES PRODUCT_NAME <target>
>              PRODUCT_BUNDLE_IDENTIFIER <bundle identifier>
>              MARKETING_VERSION <version>
>              GENERATE_INFOPLIST_FILE YES
>              INFOPLIST_FILE ""
>              INFOPLIST_KEY_CFBundleDisplayName <target>
>              INFOPLIST_KEY_NSHumanReadableCopyright <copyright>
> )
> 
> # The default property setter:
> set_target_properties(
>   <target>
>   PROPERTIES
>     FRAMEWORK_VERSION A
>     MACOSX_FRAMEWORK_IDENTIFIER <identifier>
>     [...]
> )
> ```
> 
> The arguments for the Xcode property setter are specified via:
> 
> ```
>   set(options "")
>   set(oneValueArgs "")
>   set(multiValueArgs PROPERTIES)
>   cmake_parse_arguments(PARSE_ARGV 0 _STXP "${options}" "${oneValueArgs}" "${multiValueArgs}")
> ```
> 
> I'm not opposed to the formatting being kept stable, but I am curious why the `PROPERTIES` are not indented on the next line but instead neatly kept aligned as-is.

I've added the support for providing hints how to format argument like `PROPERTIES` in `set_target_xcode_properties`. This will also be a part of 0.12.0 release.

Definition: https://github.com/BlankSpruce/gersemi/blob/master/tests/formatter/custom_command_with_hints_in_definition.out.cmake#L60
Provided formatting: https://github.com/BlankSpruce/gersemi/blob/master/tests/formatter/custom_command_with_hints_in_definition.out.cmake#L167

**Comment by BlankSpruce** [comment]
0.12.0 just got released. Thank you for constructive discussion and an opportunity to learn something new.

If there are any bugs related to indentation please open the new issue.
