### ISSUE TITLE
Add support for ignoring files

### ISSUE THREAD

**Issue by AguileraG** [BlankSpruce/gersemi#22]
Thank you for gersemi, it is a really helpful and time-saving tool.

I use gersemi in a medium-sized project, usually through the provided pre-commit hook. I noticed that CMake would always reconfigure my project afer running `pre-commit run --all-files`, even though pre-commit reported that no files had been modified.

After doing a little bit of investigation, I found out that the reconfiguration is triggered because gersemi formats some auto-generated CMake files from the build directory. This is the minimal CMake project I used to explore this issue.
```cmake
cmake_minimum_required(VERSION 3.0)

project(test-project)

add_executable(${CMAKE_PROJECT_NAME} main.c)
```

```c
#include <stdlib.h>

int main(void)
{
    return EXIT_SUCCESS;
}
```

This is the output of a gersemi dry-run after the first configuration. Only auto-generated files would be formatted, so running gersemi should not result in a reconfiguration.
```bash
$ gersemi -c .
~/test-project/build/cmake_install.cmake would be reformatted
~/test-project/build/CMakeFiles/Makefile.cmake would be reformatted
~/test-project/build/CMakeFiles/test-project.dir/DependInfo.cmake would be reformatted
~/test-project/build/CMakeFiles/3.22.1/CMakeSystem.cmake would be reformatted
~/test-project/build/CMakeFiles/test-project.dir/cmake_clean.cmake would be reformatted
~/test-project/build/CMakeFiles/3.22.1/CMakeCCompiler.cmake would be reformatted
~/test-project/build/CMakeFiles/CMakeDirectoryInformation.cmake would be reformatted
~/test-project/build/CMakeFiles/3.22.1/CMakeCXXCompiler.cmake would be reformatted
```

I would like to have the option of ignoring certain files or directories, so that the build directory and any other CMake files generated at configure or build time could be ignored by gersemi. I believe hard-coding the auto-generated files them would not work very well, because the `ExternalProject` and `FetchContent` modules could put any CMake file in the build directory.

**Comment by BlankSpruce** [comment]
I'm not sure if it's really necessary to do that for this case in particular. Honestly I consider placing `build` directory inside project directory an anti-pattern because I've seen instances where it led to problems while out-of-project `build` was usually more robust because you have to avoid baking in assumptions about `build` directory.

Having said that, let's assume that you have a good reason to go with such directory layout. If I'm reading [pre-commit doc](https://pre-commit.com/#pre-commit-run) correctly then you could avoid this by not using `--all-files` since you're interested only in proper formatting of staged files:
> Some example useful invocations:
    `pre-commit run`: this is what pre-commit runs by default when committing. This will run all hooks against currently staged files.
    `pre-commit run --all-files`: run all the hooks against all the files. This is a useful invocation if you are using pre-commit in CI.
    `pre-commit run flake8`: run the `flake8` hook against all staged files.

Another thing is that [pre-commit itself offers providing pattern for excluding certain files](https://pre-commit.com/#pre-commit-configyaml---hooks) through `exclude` key so you could improve your experience through that configuration. Disclaimer: I'm not using pre-commit daily so if I've misread docs about these two pre-commit features please let me know.

If there was a stronger example provided for implementing this kind of feature we could discuss that.

**Comment by AguileraG** [comment]
I found out the real source of my issue, it seems that `clang-format` and VSCode have some interaction that triggers the reconfiguration after I run `pre-commit`. Everything works as expected when building the project through the command line. 

I will close the issue as `gersemi` is working fine, and I do not have any other use case for ignoring files.
