### ISSUE TITLE
Inhibit favour expansion for project()?

### ISSUE THREAD

**Issue by erijo** [BlankSpruce/gersemi#27]
This CMake code:
```cmake
project(FooBar VERSION 1.2.3 LANGUAGES C CXX)
```

Is, with `--list-expansion favour-expansion`, formatted as:
```cmake
project(
    FooBar
    VERSION 1.2.3
    LANGUAGES
        C
        CXX
)
```

To me it would look better if `project` in this case was formatted as if `--list-expansion favour-expansion` wasn't given. Or is that too much of a special case?

**Comment by BlankSpruce** [comment]
@erijo 
Are you going to propose some rule enhancement to favour-expansion style so that you can "have your cake and eat it too" or we can conclude this issue?

**Comment by erijo** [comment]
It might be that what I'm actually looking for is something like favour-inlining-but-expand-sources. I.e. treat a list of source files specially and always expand them. This since it's that part that people change most often in CMakeLists.txt and the expanded list makes it easy to add new entries, sort the list, remove entries and merge. Treating source list specially also opens up the possibility for automatically sorting entries which would be nice.

As for the special case in this issue I think the easy way around it would be to either remove `LANGUAGES C CXX` since they seems to be the default if not given, or use `enable_language`.

**Comment by BlankSpruce** [comment]
I can see the merit in having expansion only for sources but practically speaking I think in a setup favouring diffs it's also beneficial to expand list of properties (key value pairs like in `set_target_properties`), compilation flags (`add_compile_options`), targets (`target_link_libraries`) and so on. I admit that `project` situation is not the most fortunate one as in there's no major gain in such formatting except maybe for obvious consistency with other commands. There's a probably a class of arguments that could see the exemption to expansion but at the moment I'm not aware of anything other "special case".

I think I will never introduce sorting for two reasons:
- I don't consider it a formatting action even if one could argue that maintaining alphabetical order improves readability (which is more or less a goal of every formatter). I think about formatters in a bit similar way to spellcheckers, they are meant to do one job and it's not paragraph reordering, grammar improvements etc. Maybe it's an open avenue for another tool, `isort` of CMake world.
- Unless I really dive into "just sources" it's somewhat risky operation in general for the build system. I recall one situation (fortunately only one) where ordering of targets in `target_link_libraries` had observable undesired effect on how the produced target behaved. I believe clean CMake files should not lead to such pitfall but unfortunately build systems are sometimes written in a very messy and convoluted way, most of the time unintentionally due to lack of experience.

**Comment by BlankSpruce** [comment]
I'll close this issue since I don't see an elegant way to achieve the intent of the first post without stating exceptions to the rule of `favour-expansion` having in mind that are certainly more classes than `source file` that benefit expansion. I'm trying to avoid special casing because I already have some special cases for some official CMake commands that do more than simple:
- option
- one value argument
- multi value argument
- section

Example: `add_custom_target` with its positional `[command1 [args1 ...]]` like in another report.

I'm open to discussion in the future if the neat way of stating the intent appears.

**Comment by jcm93** [comment]
Hi, I was just dropping in here because I've been adding gersemi to a project I'm working on, and I think it would be nice to in some way conditionally enable or disable `favour-expansion` or `favour-inlining` for different areas of CMake code. While searching around the repo I found this issue. My usecase is (predictably) enumeration of sources in particular. I certainly prefer inlining for most areas of my CMake code, but the project I'm working on has lots of top-down/header-only/unity libraries, which means a lot of enumeration of relevant source files. So I might have something like the following:

```cmake
target_sources(
  nall
  PRIVATE
    vector/access.hpp
    vector/assign.hpp
    vector/compare.hpp
    vector/core.hpp
    vector/iterator.hpp
    vector/memory.hpp
    vector/modify.hpp
    vector/utility.hpp
    vector/specialization/u8.hpp
)

target_sources(
  nall
  PRIVATE tcptext/tcp-socket.cpp tcptext/tcp-socket.hpp tcptext/tcptext-server.cpp tcptext/tcptext-server.hpp
)
```

where I would obviously prefer expansion for all of these directories, even if the directory contains only two or three files.

My idea for this would be not to expand based on any internal heuristic ('expand for sources, inline for project()'), but perhaps just make it hintable? Perhaps something like

```cmake
# gersemi: expand-on
target_sources(
  nall
  PRIVATE tcptext/tcp-socket.cpp tcptext/tcp-socket.hpp tcptext/tcptext-server.cpp tcptext/tcptext-server.hpp
)
# gersemi: expand-default
```

My sources are typically enumerated in their own files for when this is most tedious, so it could often be as much more simple, i.e.:

```cmake
# gersemi: expand-on
include(cmake/sources.cmake)
# gersemi: expand-default
```

The implementation sketch is just the first thing I thought of, and it may be very bad. Mainly, I just wanted to add onto this issue to say that conditional behavior for expansion vs. inlining is something that I also desire. Thanks for reading.

**Comment by BlankSpruce** [comment]
Interesting approach. I'll definitely ponder on that.

**Comment by BlankSpruce** [comment]
There are a few things to consider:
1. I wonder how often `favour-inlining` with combination of relatively smaller `line-length` would usually accomplish "the right thing". I'm wondering about that in particular because it's not the most elegant to sprinkle here and there these additional hints. Consider this:
```cmake
# line_length: 60, list_expansion: favour-inlining
project(FooBar VERSION 1.2.3 LANGUAGES C CXX)

target_sources(
  nall
  PRIVATE
    vector/access.hpp
    vector/assign.hpp
    vector/compare.hpp
    vector/core.hpp
    vector/iterator.hpp
    vector/memory.hpp
    vector/modify.hpp
    vector/utility.hpp
    vector/specialization/u8.hpp
)

target_sources(
  nall
  PRIVATE 
    tcptext/tcp-socket.cpp 
    tcptext/tcp-socket.hpp 
    tcptext/tcptext-server.cpp 
    tcptext/tcptext-server.hpp
)

target_sources(
  two_sources 
  PRIVATE
   tcptext/foo.cpp
   tcptext/bar.cpp
)

target_sources(just_one_source PRIVATE tcptext/foo.cpp)
```

2. I'm not sure what should be the order of precedence in case of local style override. Currently there is `default < .gersemirc < command line` for any of the configuration knobs. Command line has the highest precedence because I've thought it's beneficial to have that override power when user is experimenting with the tool or debugging some issue. Where would local override land in this? I think there are only two viable alternatives and I'm not sure yet which one is better:
a) `default < .gersemirc < command line < local override`
b) `default < .gersemirc < local override < command line`

3. Assuming that some order of precedence is selected I imagine in most of the cases you'd rather want to say "for all files in this project I want `target_sources` to be always expanded" rather than meticulously go through every single file to add that hint. I think that any such hint (like `on/off`) should be truly exceptional. This leads me to alternative approach which is configuration knob something along the lines (names are subject to change):
```yaml
# .gersemirc
list_expansion: favour-inlining
commands_with_favour_expansion: 
- "target_.*"
- "add_library"
- "add_executable"
```
You'd spell regexp for the command you'd want to be treated differently. I'm not a huge fan of configuration knobs but [I've been wrong about that at least once](https://github.com/BlankSpruce/gersemi/issues/15) so I'm leaving it open for further consideration.

**Comment by jcm93** [comment]
A shorter line length would indeed create the desired result for most areas of my code that enumerate files. But I would then find myself wanting the longer line length for areas with internal logic, helper functions, etc. So I think I would be back then to the same problem of wanting one type of formatting in one area, and another in another.

I do like what you propose in 3. I personally don't think it falls under excessive configuration, and it certainly covers everything I would like, so I like it :P Since enumerating certain things exhaustively ends up being a fairly core part of modern CMake, I don't see the harm in a bit of convenience around it :P

If you were to go the route in 3), I don't think that I see a need for code-level style overrides anymore at all (beyond on/off), at least from my point of view. So possibly you would not even have to consider the issue of local vs. command line precedence.

**Comment by BlankSpruce** [comment]
I've just recalled [some clever technique](https://github.com/BlankSpruce/gersemi/issues/16#issue-2166988092) to break lines which works almost like a hint. Just put empty comment `#` in the thing you want to expand. Consider this:
```cmake
# line_length: 120, list_expansion: favour-inlining
# normal inlining
project(FooBar VERSION 1.2.3 LANGUAGES C CXX)

# force simple expansion
project(
    FooBar #
    VERSION 1.2.3
    LANGUAGES C CXX
)

# force expansion on LANGUAGES
project(
    FooBar
    VERSION 1.2.3
    LANGUAGES #
        C
        CXX
)

# normal inlining
target_sources(nall PUBLIC vector/access.hpp vector/assign.hpp PRIVATE vector/compare.hpp vector/core
.hpp)

# force expansions
target_sources(
    nall
    PUBLIC #
        vector/access.hpp
        vector/assign.hpp
    PRIVATE #
        vector/compare.hpp
        vector/core.hpp
)

# weird but possible, PUBLIC expanded, PRIVATE inlined
target_sources(
    nall
    PUBLIC #
        vector/access.hpp
        vector/assign.hpp
    PRIVATE vector/compare.hpp vector/core.hpp
)
```

**Comment by jcm93** [comment]
Hey there! I am back to this as I'm doing some finalization of formatting for my project. I will likely end up adopting the empty comment to force expansion for commands that I want to always be expanded regardless of line length.

However, I think longer term, something like what you proposed [here](https://github.com/BlankSpruce/gersemi/issues/27#issuecomment-2370813453) in 3) would still be more ideal. If I adopt the # to force expansion ad-hoc, then my code becomes littered with what are effectively formatter hints, which I would have liked to avoid. 

Further, if I ever change the line length, the areas where the empty comment is necessary will change, so for consistency I might require it in every call to a command I want always expanded, which is a bit weird.

I haven't been following development here super closely, so if some other way has been introduced to favor expansion for certain commands, do let me know (or I'll find it).

**Comment by jcm93** [comment]
Just adding another example for sake of illustration:

https://gist.github.com/jcm93/4795ed38f79398b1ca4b1132d8353f43 - This is how I'd prefer things to be laid out for my source enumeration, here using the comments to force expansion

https://gist.github.com/jcm93/58f060225ec5b4ae5b7ca945cc7db997 - How gersemi will format it by default (line length of 120).

There are a lot of files like this in the project that solely enumerate files in this fashion.
