### ISSUE TITLE
Cannot disable unknown command warnings with definitions because of conditional overloading

### ISSUE THREAD

**Issue by PatTheMav** [BlankSpruce/gersemi#33]
At `obs-studio` we use OS-specific branching and conditional includes in our CMake list with function inheritance to create an environment in which sub-projects can use one common API of custom functions while using OS-specific implementations.

This means that the same custom function is implemented in multiple files (one for each supported OS) and some functions implicitly use CMake's behaviour of keeping a reference to overloading functions around (prefixed with an underscore), but _those_ functions are also warned about as "unknown" (also those can never be explicitly defined because it's implicit, internal, CMake behaviour).

With gersemi 0.14.0 one can only choose between getting a list of files requiring formatting changes _and_ warnings about unknown functions or entirely quiet output, so one has to add references to CMake files with function definitions for these "unknown" functions.

In our case this leads to gersemi not warning about unknown functions anymore, but instead printing a warning about "conflicting definitions".

We also get a warning about an "unknown command" for macros defined in the same file.

---

Because we required specific (and unified) output of formatting issues on CI, I had to create a shell wrapper function around gersemi to invoke it only once with multiple files and then parse the output for files that required changes.

This worked fine until version 0.14.0, but the new warnings break the assumption of a "single line warning printed per checked file". I'm also not sure whether such linting behaviour should be enabled by default as it goes beyond the scope of a formatter/format checker.

**Comment by PatTheMav** [comment]
To add some more context: The same function will be defined with different _actual_ implementations for each supported OS, but depending on which file is included, only one of them will actually be processed by the script.

We make active use of `include` and include guards to compose a single implementation of our CMake API for each operating system, but some functions will only be defined for a specific OS and we also pull in some sub-projects conditionally (e.g. for specific OS and architecture).

Thus _every_ file that is included in any way also needs to be supplied to gersemi's `definitions` setting (which will need to contain practically all CMake files ever included by any other file) because it will not be able to resolve all function calls.

But because it also cannot differentiate if/when functions will actually be called, all OS-specific includes need to be made available to gersemi at all times, leading to conflicting function definitions.

**Comment by BlankSpruce** [comment]
Since I'm not sure I'll have the time to discuss issue further before the weekend I will leave some questions and if you find time to answer them that'd be helpful and I wouldn't be completely empty-handed later on.

> At obs-studio we use OS-specific branching and conditional includes in our CMake list with function inheritance to create an environment in which sub-projects can use one common API of custom functions while using OS-specific implementations.

If I'm understanding that part correctly TLDR version is: there are multiple definitions of the same function/macro and `gersemi` requires exactly one in `definitions`.

Currently there is a very basic notion of "conflicting defintions" used in the formatter. For the remainder of this issue I will be referring to some made up commands to illustrate what's going on and if you have something to expand on the question please refer to those or provide your own example.
1) Are those OS-specific definitions overlapping in the sense that there are some keywords that are shared and some that are specific to the OS? Example:
```cmake
## CHARACTER and PLAYED_BY keywords are shared
# Linux
# movie_add_character(<movie> CHARACTER <name> [PLAYED_BY <actor>] [PROTAGONIST | SUPPORTING])
movie_add_character(DjangoUnchained CHARACTER DrSchultz PLAYED_BY ChristophWaltz SUPPORTING)

# Windows
# movie_add_character(<movie> CHARACTER <name> [PLAYED_BY <actor>] [COMES_FROM_REGION <region>])
movie_add_character(DjangoUnchained CHARACTER DrSchultz PLAYED_BY ChristophWaltz COMES_FROM_REGION Germany)
```

2) Is it possible for those definitions to have different meaning for the same keyword depending on the OS? Example:
```cmake
# Linux, here ACCENT is option keyword meaning "character speaks with some accent different than usual in given setting"
# book_add_character(<book> CHARACTER <name> [ACCENT])
book_add_character(HarryPotter CHARACTER RonWeasley ACCENT)

# Windows, here ACCENT is one value keyword meaning "character speaks with exactly <accent>"
# book_add_character(<book> CHARACTER <name> [ACCENT <name>])
book_add_character(HarryPotter CHARACTER RonWeasley ACCENT Scottish)
```

3) Is it possible for those definitions that for one OS there is no keyword in the definition and on the other there are? Example:
```cmake
# Linux
# do_stuff_with_files(<file> [<file> ...])
do_stuff_with_files(file1.cmake file2.cmake file3.cmake)

# Windows
# do_stuff_with_files(FILES <file> [<file> ...] [ARGS_FOR_STUFF <arg> [<arg> ...]])
do_stuff_with_files(FILES file1.cmake file2.cmake file3.cmake ARGS_FOR_STUFF foo bar baz)
```

4) Is it possible that for one OS such definition is a macro and another OS it's a function? Example:
```cmake
# Linux
function(frombulate)
   ...
endfunction()

# Windows
macro(frombulate)
   ...
endmacro()
```

5) Would it satisfy your needs to have selectable notion of "formatted file" to suppress some warnings namely (names are subject to change):
- strict === something along the lines what happened since 0.14.0 were custom definitions are mandatory
- weak === lack of custom definition doesn't produce a warning

Before you answer the last question I'd like to emphasize that despite introduction of warnings in 0.14.0 unknown commands [were and still are barely formatted](https://github.com/BlankSpruce/gersemi/issues/30) since I haven't implemented magic yet to conjure out of thin air intended and obvious for humans formatting.

Answers to questions 1-4 might help me better understand the topic and possibly allow multiple definitions of command signature to be supplied as long as they can be reliably reconciled.

By the way issues like those are exactly the reason why I think that CMake language isn't really automation friendly even though CMake itself is very convenient to work with.

**Comment by PatTheMav** [comment]
> Since I'm not sure I'll have the time to discuss issue further before the weekend I will leave some questions and if you find time to answer them that'd be helpful and I wouldn't be completely empty-handed later on.

Yeah, no rush. It's your project, tackle it however/whenever you see fit.

> 
> > At obs-studio we use OS-specific branching and conditional includes in our CMake list with function inheritance to create an environment in which sub-projects can use one common API of custom functions while using OS-specific implementations.
> 
> If I'm understanding that part correctly TLDR version is: there are multiple definitions of the same function/macro and `gersemi` requires exactly one in `definitions`.

Yes, that is the first part of the observed issue.

> 
> Currently there is a very basic notion of "conflicting defintions" used in the formatter. For the remainder of this issue I will be referring to some made up commands to illustrate what's going on and if you have something to expand on the question please refer to those or provide your own example.
> 
> 1. Are those OS-specific definitions overlapping in the sense that there are some keywords that are shared and some that are specific to the OS? Example:
> 
> ```cmake
> ## CHARACTER and PLAYED_BY keywords are shared
> # Linux
> # movie_add_character(<movie> CHARACTER <name> [PLAYED_BY <actor>] [PROTAGONIST | SUPPORTING])
> movie_add_character(DjangoUnchained CHARACTER DrSchultz PLAYED_BY ChristophWaltz SUPPORTING)
> 
> # Windows
> # movie_add_character(<movie> CHARACTER <name> [PLAYED_BY <actor>] [COMES_FROM_REGION <region>])
> movie_add_character(DjangoUnchained CHARACTER DrSchultz PLAYED_BY ChristophWaltz COMES_FROM_REGION Germany)
> ```

No, the function signatures are identical, the function _body_ is different. The signatures need to be identical because they are being called from sub-projects that have (or should have) no concept of different platforms.

E.g. we have a custom function `set_target_properties_obs` that takes the same arguments for all platforms, but internally does a lot of housekeeping for OS-specific packaging and sets up install commands, custom targets, post-build commands, etc.

It is implemented 3x in different CMake files which are placed in different directories, each of which is conditionally added to `CMAKE_MODULE_PATH`: https://github.com/obsproject/obs-studio/blob/master/cmake/common/osconfig.cmake

>  2. Is it possible for those definitions to have different meaning for the same keyword depending on the OS? Example:
> 
> ```cmake
> # Linux, here ACCENT is option keyword meaning "character speaks with some accent different than usual in given setting"
> # book_add_character(<book> CHARACTER <name> [ACCENT])
> book_add_character(HarryPotter CHARACTER RonWeasley ACCENT)
> 
> # Windows, here ACCENT is one value keyword meaning "character speaks with exactly <accent>"
> # book_add_character(<book> CHARACTER <name> [ACCENT <name>])
> book_add_character(HarryPotter CHARACTER RonWeasley ACCENT Scottish)
> ```

See above, I can see how or why someone _might_ implement this, but in our case the function signatures need to be stable for each implementation.

>  3. Is it possible for those definitions that for one OS there is no keyword in the definition and on the other there are? Example:
> 
> ```cmake
> # Linux
> # do_stuff_with_files(<file> [<file> ...])
> do_stuff_with_files(file1.cmake file2.cmake file3.cmake)
> 
> # Windows
> # do_stuff_with_files(FILES <file> [<file> ...] [ARGS_FOR_STUFF <arg> [<arg> ...]])
> do_stuff_with_files(FILES file1.cmake file2.cmake file3.cmake ARGS_FOR_STUFF foo bar baz)
> ```

It could functionally happen, but in our case the optional arguments would be optional _globally_ and not just in specific implementations (i.e. the signature needs to be the same).

>  4. Is it possible that for one OS such definition is a macro and another OS it's a function? Example:
> 
> ```cmake
> # Linux
> function(frombulate)
>    ...
> endfunction()
> 
> # Windows
> macro(frombulate)
>    ...
> endmacro()
> ```

We actually overload a function with a macro on purpose in a single instance because we need the macro body to run in the calling scope and not create a new function scope.

This is to use a function common in our CMake files as a "hook" for overloading to do an early `return`.

>  5. Would it satisfy your needs to have selectable notion of "formatted file" to suppress some warnings namely (names are subject to change):
> 
> * strict === something along the lines what happened since 0.14.0 were custom definitions are mandatory
> * weak === lack of custom definition doesn't produce a warning
> 
> Before you answer the last question I'd like to emphasize that despite introduction of warnings in 0.14.0 unknown commands [were and still are barely formatted](https://github.com/BlankSpruce/gersemi/issues/30) since I haven't implemented magic yet to conjure out of thin air intended and obvious for humans formatting.

As I mentioned in my comment on the other issue, I think default "argument formatting" should be applied even (or especially) if it makes the function call look "ugly" when formatted. This would serve as an incentive for users to provide an argument signature to the formatter.

The default formatting would be stable and deterministic (given the same custom function in two different CMake files, it will be "uglified" in the same way) and the burden on getting it to look how the user wants it to is with the user itself.

To that end I'd say that the `definitions` setting is a very elegant idea in principle, but it runs into one of the issues I outlined here:

We have custom functions defined in different cmake files of the same name which exist for 3 different platforms (using the module path to ensure that an `include` will only find the OS-specific one), but not all platforms need _all_ the functions, so some are only defined in the Windows-specific variant and some are only defined in the macOS-specific one.

So to provide gersemi with a union of all existing custom functions, we'd have to provide all helpers which will lead to the conflicts outlined above because it will need to parse all included files to generate definitions for all custom functions.

**Comment by BlankSpruce** [comment]
> As I mentioned in my comment on the other issue, I think default "argument formatting" should be applied even (or especially) if it makes the function call look "ugly" when formatted. This would serve as an incentive for users to provide an argument signature to the formatter.

If I had a magic wand I would avoid separate definitions and instead delegate some stuff to helper functions but most likely I'm not aware of the choices that were made in OBS project to deal with that this way. Now that I see what you're dealing with I think allowing weaker notion of formatted file is the right direction. I'll probably introduce that as an opt-out setting so that it's a conscious choice. Caching bug mentioned in other issue will have to be of course fixed as well.

> If I were to "fix" the issue on my own, I'd have to create a "dummy" CMake file that contains all the custom functions used throughout the codebase and only provide that one as a definition to gersemi (though that would at least require me to know the minimum requirements needed for a function to be properly parsed by it).

I'd certainly recommend considering this approach at least for these custom commands that have multiple definitions. Sometimes I call this stub definition and I'd define it like this:
```cmake
function(frombulate)
    # gersemi: hints { QUX: pairs, QUY: command_line }
    set(options FOO BAR)
    set(oneValueArgs BAZ)
    set(multiValueArgs QUX QUY QUZ)
    cmake_parse_arguments(prefix "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    message(FATAL_ERROR "Stub definition, don't use it")
endfunction()
```
Of course this has the disadvantage that you are prone to desynchronization between real implementations and the stub one in terms of supported keywords. Trade-offs need to be considered because `import magic` is not available yet in Python. :smile: 

Regarding the minimum requirements and what's possible take a look at ["Let's make a deal"](https://github.com/BlankSpruce/gersemi?tab=readme-ov-file#lets-make-a-deal) section of README. I also mention there the stub definition trick.

**Comment by PatTheMav** [comment]
Yeah the stub definition idea came to me only recently, it is a good-enough solution for complex scenarios and as I mentioned probably the better approach than to come up with a custom schema to define function arguments (which would represent _another_ parser for yet another abstraction of CMake internals).

Just parsing `cmake_parse_arguments` instances has the benefit that it also incentivises developers to use that for complex function argument parsing in their CMake files as well.

**Comment by BlankSpruce** [comment]
I haven't yet released new version on PyPI but master branch has these improvements:
- `--cache`/`--no-cache` (command line) and `cache` (.gersemirc) to control whether cache is used at all, cache will stay enabled by default
- `--required-definitions/--no-required-definitions` and `required_definitions` to control whether `gersemi` will warn about unknown custom commands, definitions will be required by default
- bugfix: even when cache is enabled only formatted files without warnings will be cached

I haven't yet decided whether `required-definitions` should impact return code of `--check` and whether file should be rewritten when `--in-place` is used.

**Comment by BlankSpruce** [comment]
After some consideration I've changed the name from `required-definitions` to `warn-about-unknown-commands` since my intention is that formatter will fallback to do the second best thing which is fixing at least something instead of nothing. In other words lack of definition is not an error as if to mimick SFINAE from C++.

0.15.0 got released. If there are any issues just let me know.
